name: CI-master

on:
  push:
    branches: [master]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Runs a single command using the runners shell
      - name: yarn install
        run: |
          yarn --prefer-offline --frozen-lockfile --no-progress --non-interactive

      # - name: Lint
      #   run: yarn lint
      - name: Echo directory
        run: echo "$(env.GITHUB_WORKSPACE)"
      - name: Build
        run: yarn build


      #l -X POST -H 'Content-type: application/json' --data '{"text":"'"$GITHUB_WORKFLOW"' Failed for `${{ github.event.repository.name }}` - <'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'|View Run>"}' https://hooks.slack.com/services/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
