name: CI-master

on:
  push:
    branches: [master]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      # Runs a single command using the runners shell
      - name: yarn install
        run: |
          yarn --prefer-offline --frozen-lockfile --no-progress --non-interactive

      - name: Echo directory
        run: |
          ls ./src
          echo "Hello World"
          echo "{{ $GITHUB_WORKSPACE/src }} "

      - name: Build
        run: yarn build